'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FreeSCAN.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1375121_10151880936949421_1072291165_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1375121_10151880936949421_1072291165_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appstore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appstore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                                      &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''  &lt;head&gt;
        '''    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        '''    &lt;title&gt;TITLEBARSPEC&lt;/title&gt;
        '''
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''      #map-canvas {
        '''        height: 500px;
        '''      }
        '''    &lt;/style&gt;
        '''
        '''    &lt;script type=&quot;text/javascript&quot; src=&quot;http://www.google.com/jsapi?autoload={&apos;modules&apos;:[{name:&apos;maps&apos;,version:3,other_params:&apos;sensor=false&apos;}]}&quot;&gt;&lt;/script&gt;
        '''    &lt;script type=&quot;text/javascript&quot;&gt;
        '''            function DistanceWidget(map [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GPSView() As String
            Get
                Return ResourceManager.GetString("GPSView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property groupico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("groupico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property My_Documents1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("My_Documents1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                                      &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''  &lt;head&gt;
        '''    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        '''    &lt;title&gt;GPS System Summary&lt;/title&gt;
        '''
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''                #map-canvas {
        '''          height: 1000px;
        '''      }
        '''    &lt;/style&gt;
        '''
        '''    &lt;script type=&quot;text/javascript&quot; src=&quot;http://www.google.com/jsapi?autoload={&apos;modules&apos;:[{name:&apos;maps&apos;,version:3,other_params:&apos;sensor=false&apos;}]}&quot;&gt;&lt;/script&gt;
        '''    &lt;script type=&quot;text/javascript&quot;&gt;
        '''            function [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SystemPlotter() As String
            Get
                Return ResourceManager.GetString("SystemPlotter", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
